---
repo-name: peripherals-kinetic-discussions
categories:
- Social
- Chat
display-name: Kinetic Discussions
manufacturer: Kinetic Data
description: The Discussions (real time chat) component of the Kinetic Platform.
